### ISSUE TITLE
Feat: create styleguide rule for providers

### ISSUE THREAD

**Issue by tuxmachine** [TrilonIO/eslint-plugin#13]
# Description

Large teams can have the desire to limit or enforce a particular style of creating providers; e.g. banning request-scoped providers.

# Acceptance Criteria

tbd needs more refinement

**Comment by tuxmachine** [comment]
Perhaps we can take https://github.com/nestjs/nest/pull/12753 into account

**Comment by thiagomini** [comment]
Duplicate of #24
