### ISSUE TITLE
Feat: warn about usage of `forwardRef`

### ISSUE THREAD

**Issue by tuxmachine** [TrilonIO/eslint-plugin#18]
# Description

Circular dependencies are a clear sign of code that should be refactored because e.g. a class has grown too big or separation of concerns is violated.

# Acceptance Criteria

Invalid code:

```ts
import { forwardRef } from '@nestjs/common';

@Injectable()
export class CatsService {
  constructor(
    @Inject(forwardRef(() => CommonService)) // ⚠️ Circular-dependency detected
    private commonService: CommonService,
  ) {}
}


@Module({
  imports: [forwardRef(() => CatsModule)], // ⚠️ Circular-dependency detected
})
export class CommonModule {}
```

Would we also be able to detect this attempt to dodge detection? 🤔

```ts
import { forwardRef as silentForwardRef } from '@nestjs/common';
```

**Comment by thiagomini** [comment]
Loved the idea, @tuxmachine. And yes, we could detect renaming, just a bit more of processing
