### ISSUE TITLE
Protect Main Branch and configure pipeline

### ISSUE THREAD

**Issue by thiagomini** [TrilonIO/eslint-plugin#4]
# Description

We must protect the main branch and ensure PRs run a basic CI Pipeline (required) before merging.

**Comment by tuxmachine** [comment]
I think this one is configured now via the branch protection rules. You need to type the first character of the workflow to trigger the autocomplete. 

![image](https://github.com/TrilonIO/eslint-plugin/assets/692443/7a7c21db-f66f-4ab6-844d-18959b2f6cc8)

**Comment by thiagomini** [comment]
Oh, did you configure that? Can I close this ticket then, @tuxmachine?
